stages:
  - tests
  - deploy

before_script:
  - mkdir -pvm 0700 ~/.ssh
  - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
  - eval `ssh-agent -s`
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

after_script:
  - rm -Rfv ~/.ssh

tests:
  stage: tests
  image: python:alpine
  script:
    - python -m unittest discover

autoversion:
  stage: deploy
  image: nmartignoni/makaron
  script:
    - autoversion.sh
  except:
    - tags

pypi:
  stage: deploy
  image: python:alpine
  before_script: []
  script:
    - echo "[server-login]" >> ~/.pypirc
    - echo "username=" ${PYPI_USER} >> ~/.pypirc
    - echo "password=" ${PYPI_PASSWORD} >> ~/.pypirc
    - python setup.py sdist upload
    - echo "" > ~/.pypirc && rm ~/.pypirc
  after_script:
    - rm -vf ~/.pypirc
  only:
    - /^\d+\.\d+\.\d+$/
  except:
    - branches
