stages:
  - tests
  - deploy

tests:
  stage: tests
  image: python:alpine
  script:
    - pip install coverage
    - python setup.py install
    - python -m unittest discover
    - makaron

coverage:
  stage: tests
  image: python:alpine
  script:
    - python setup.py install
    - coverage run --source=makaron -m unittest discover -s tests/
    - coverage report -m
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

autoversion:
  stage: deploy
  image: nmartignoni/makaron
  before_script:
    - mkdir -pvm 0700 ~/.ssh
    - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
    - eval `ssh-agent -s`
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
  after_script:
    - rm -Rfv ~/.ssh
  script:
    - autoversion.sh
  except:
    - tags

pypi:
  stage: deploy
  image: python:alpine
  script:
    - echo "[server-login]" >> ~/.pypirc
    - echo "username=" ${PYPI_USER} >> ~/.pypirc
    - echo "password=" ${PYPI_PASSWORD} >> ~/.pypirc
    - python setup.py sdist upload
    - echo "" > ~/.pypirc && rm ~/.pypirc
  after_script:
    - rm -vf ~/.pypirc
  only:
    - /^\d+\.\d+\.\d+$/
  except:
    - branches
